### ISSUE TITLE
example distribution not able to run out of the box

### ISSUE THREAD

**Issue by manzke** [techatspree/chameRIA#3]
Hi guys,

I have downloaded the preconfigured example distribution 1.5.0., but it is not able to run out of the box.

My machine is a Win7 64-Bit. I have a 64- and 32-Bit Java installed. After changing to the 32-Bit Java, ChameRIA tried to start.

But it ended with:

Loading library: 'QtWebKit4.dll'...
- using 'com.trolltech.qt.library-path-override
  
  ```
  at com.trolltech.qt.internal.NativeLibraryManager.loadNativeLibrary(NativeLibraryManager.java:431)
  at com.trolltech.qt.internal.NativeLibraryManager.loadQtLibrary(NativeLibraryManager.java:355)
  at com.trolltech.qt.Utilities.loadQtLibrary(Utilities.java:44)
  at com.trolltech.qt.Utilities.loadQtLibrary(Utilities.java:40)
  at com.trolltech.qt.webkit.QtJambi_LibraryInitializer.<clinit>(QtJambi_LibraryInitializer.java:10)
  ... 7 more
  ```
  
  Caused by: java.lang.UnsatisfiedLinkError: D:\Downloads\chameria-default-distribution-1.5.0-win\qt\bin\QtWebKit4.dll: Can't find dependent libraries
      at java.lang.ClassLoader$NativeLibrary.load(Native Method)
      at java.lang.ClassLoader.loadLibrary0(Unknown Source)
      at java.lang.ClassLoader.loadLibrary(Unknown Source)
      at java.lang.Runtime.load0(Unknown Source)
      at java.lang.Runtime.load(Unknown Source)
      at com.trolltech.qt.internal.NativeLibraryManager.loadLibrary_helper(NativeLibraryManager.java:478)
      at com.trolltech.qt.internal.NativeLibraryManager.loadNativeLibrary(NativeLibraryManager.java:426)

What dependencies is the QtWebKit searching for? Is there any setup needed, which register the DLLs? 

Bye,
Daniel

**Comment by cescoffier** [comment]
Hi,

Could you retry after installing the C++ redistributable package for Windows: http://www.microsoft.com/download/en/details.aspx?displaylang=en&id=29

Regards,

Clement

**Comment by manzke** [comment]
Didn't worked. I tried vc redist 2008 and 2010.

**Comment by manzke** [comment]
It only worked after installing QT 4.6.4 from the Nokia side and adding it also to the path.

**Comment by cescoffier** [comment]
That means we're forgetting a native library. If you have any idea of which one, please let me know.
You can use http://www.dependencywalker.com/ to find the required librairies.

Thanks

**Comment by manzke** [comment]
I'll retest it on a new machine.

**Comment by manzke** [comment]
Hey guys, after some investigation, I found it.

adding this to the ;.\qt\bin Path in your launch script, everything works fine for me.

Not working: SET PATH=.\lib;%PATH%
Working: SET PATH=.\lib;.\qt\bin;%PATH%

**Comment by cescoffier** [comment]
Wow ! That's right... it's a bug... as we did the same trick in our products... 

Will fix it ASAP ! Thanks !

**Comment by manzke** [comment]
Just for your information. It is also able to run with qtjambi 1.7.0 beta 3 for windows.

**Comment by cescoffier** [comment]
Hi,

I've fixed the PATH issue. Thanks ! 

About qtjambi, I'm waiting to get a QTJambi version available for mac, linux and windows.
