### ISSUE TITLE
Build and run from source doesn't work

### ISSUE THREAD

**Issue by jbellmann** [techatspree/chameRIA#4]
Hi,

I tried the instructions on http://chameria.spree.de to build an run chameRIA. First I had to skip testing in the build. Some tests failed. Without tests the build succeeded. But launching produces the following output:

```
$ ./launch-mac.sh 

    ============================
    |                          |
    |   Welcome to ChameRIA    |
    |                          |
    ============================


Exception in thread "main" java.lang.NoClassDefFoundError: com/trolltech/qt/gui/QApplication
    at de.akquinet.chameria.launcher.Launcher.main(Launcher.java:77)
Caused by: java.lang.ClassNotFoundException: com.trolltech.qt.gui.QApplication
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 1 more
java.io.FileNotFoundException: chameleon-cache/.lock (No such file or directory)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:194)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:145)
    at java.io.FileWriter.<init>(FileWriter.java:73)
    at de.akquinet.chameria.launcher.ChameRIA.deleteLock(ChameRIA.java:231)
    at de.akquinet.chameria.launcher.ChameRIA.stop(ChameRIA.java:172)
    at de.akquinet.chameria.launcher.Launcher$1.run(Launcher.java:240)
    at java.lang.Thread.run(Thread.java:680)


    =========================
    |   ChameRIA  stopped   |
    =========================


$ 
``
`

Cheers Jörg
```

**Comment by cescoffier** [comment]
Hi,

I've reproduce the issue. It was introduced during the release.
To fix it, just update the version (to the right version) of qt artifacts in the shell script:

```
export CLASSPATH=core/chameria-launcher-1.5.1-SNAPSHOT.jar:core/core-0.4.0.jar:core/logback-classic-   0.9.24.jar:core/org.osgi.compendium-4.2.0.jar:core/logback-core-0.9.24.jar:core/org.apache.felix.framework-3.0.2.jar:core/slf4j-api-1.6.1.jar:qt/qtjambi-4.6.0-jnlp.jar:qt/qtjambi-util-4.6.0.jar
```

I will fix it later today in the master branch.

**Comment by jbellmann** [comment]
Ok, that fixes the problem and the app is starting.
Thank you.
